#ifndef __UNCURL_CONST_H
#define __UNCURL_CONST_H

#define UNCURL_PORT 80
#define UNCURL_PORT_S 443

enum uncurl_scheme {
	UNCURL_NONE  = 0,
	UNCURL_HTTP  = 1,
	UNCURL_HTTPS = 2,
	UNCURL_WS    = 3,
	UNCURL_WSS   = 4,
};

enum uncurl_header_type {
	UNCURL_REQUEST  = 0,
	UNCURL_RESPONSE = 1,
};

enum ws_opcode {
	UNCURL_WSOP_CONTINUE = 0x0,
	UNCURL_WSOP_TEXT     = 0x1,
	UNCURL_WSOP_BINARY   = 0x2,
	UNCURL_WSOP_CLOSE    = 0x8,
	UNCURL_WSOP_PING     = 0x9,
	UNCURL_WSOP_PONG     = 0xa,
};

enum uncurl_option {
	UNCURL_OPT_MAX_HEADER        = 0,
	UNCURL_OPT_MAX_BODY          = 1,

	UNCURL_NOPT_READ_TIMEOUT     = 100,
	UNCURL_NOPT_CONNECT_TIMEOUT  = 101,
	UNCURL_NOPT_ACCEPT_TIMEOUT   = 102,
	UNCURL_NOPT_READ_BUF         = 103,
	UNCURL_NOPT_WRITE_BUF        = 104,
	UNCURL_NOPT_KEEPALIVE        = 105,
	UNCURL_NOPT_TCP_NODELAY      = 106,

	UNCURL_TOPT_VERIFY_HOST      = 200,
};

#endif
